# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(549, 362)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.asas = QtWidgets.QTabWidget(self.centralwidget)
        self.asas.setGeometry(QtCore.QRect(0, 0, 551, 361))
        self.asas.setIconSize(QtCore.QSize(16, 16))
        self.asas.setElideMode(QtCore.Qt.ElideRight)
        self.asas.setTabBarAutoHide(False)
        self.asas.setObjectName("asas")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.asas.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.asas.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        MainWindow.setStyleSheet("#MainWindow{background-color:white}")
        self.retranslateUi(MainWindow)
        self.asas.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.asas.setTabText(self.asas.indexOf(self.tab), _translate("MainWindow", "游戏"))
        self.asas.setTabText(self.asas.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
